<div style="background-color: #f8fafc; padding: 24px 30px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; line-height: 1.6;">
    <p style="margin: 0 0 6px 0;">This is an automated notification generated by the <strong>PhD Thesis Portal System (PTS)</strong>.</p>
    <p style="margin: 0; color: #94a3b8; font-size: 11px;">Please do not reply directly to this email. For technical or academic queries, please reach out to the academic office.</p>
</div>
